"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_11
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_11 guid: (GUID fromString: '{B4E236BE-BE04-48DD-AC35-D4CE1BB763C5}')!
LibGciRpc64_3_2_11 comment: ''!
!LibGciRpc64_3_2_11 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_11 class methodsFor!

displayName

	^'64-bit 3.2.11'.
!

fileNameSearch

	^'libgcirpc-3.2.11-32.dll'.
! !
!LibGciRpc64_3_2_11 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_11 class categoriesFor: #fileNameSearch!public! !

