"Filed out from Dolphin Smalltalk 7"!

MCFileBasedRepository subclass: #MCDirectoryRepository
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MCDirectoryRepository guid: (GUID fromString: '{8B1B9EE6-FA9A-4E55-93E0-873C1F44B600}')!
MCDirectoryRepository comment: ''!
!MCDirectoryRepository categoriesForClass!Unclassified! !
!MCDirectoryRepository methodsFor!

updateVersionDialogTabIn: aMCVersionDialog

	aMCVersionDialog updateDirectoryTabWith: self.
! !
!MCDirectoryRepository categoriesFor: #updateVersionDialogTabIn:!public! !

