"Filed out from Dolphin Smalltalk 7"!

QWORDField subclass: #OopType64Field
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OopType64Field guid: (GUID fromString: '{7ED7D17B-7FC5-4857-89C3-5A27AC9DE8AD}')!
OopType64Field comment: ''!
!OopType64Field categoriesForClass!Unclassified! !
!OopType64Field methodsFor!

fieldClass

	^OopType64.! !
!OopType64Field categoriesFor: #fieldClass!public! !

