"Filed out from Dolphin Smalltalk 7"!

GsHostProcess subclass: #SharedPageCacheMonitor
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SharedPageCacheMonitor guid: (GUID fromString: '{81611FF5-3795-4F5A-83D0-98C55159048A}')!
SharedPageCacheMonitor comment: ''!
!SharedPageCacheMonitor categoriesForClass!Unclassified! !
!SharedPageCacheMonitor methodsFor!

processType

	^'Cache'.
! !
!SharedPageCacheMonitor categoriesFor: #processType!public! !

!SharedPageCacheMonitor class methodsFor!

type

	^'cache'.
! !
!SharedPageCacheMonitor class categoriesFor: #type!public! !

