"Filed out from Dolphin Smalltalk 7"!

JadeSessionManager subclass: #ContactsSessionManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ContactsSessionManager guid: (GUID fromString: '{639E76E3-B3C9-4DCE-A9EB-F50B3D878AC8}')!
ContactsSessionManager comment: ''!
!ContactsSessionManager categoriesForClass!Unclassified! !
!ContactsSessionManager class methodsFor!

mainShellClass

	^ContactsLoginShell.
! !
!ContactsSessionManager class categoriesFor: #mainShellClass!public! !

