"Filed out from Dolphin Smalltalk 7"!

Shell subclass: #ContactsShell
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ContactsShell guid: (GUID fromString: '{f11b768d-f9fa-4272-b4fa-17ec49f4d7ac}')!
ContactsShell comment: ''!
!ContactsShell categoriesForClass!Unclassified! !
!ContactsShell class methodsFor!

icon

	^Icon fromFile: 'icons\GS32.ico'.
! !
!ContactsShell class categoriesFor: #icon!public! !

