"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw65
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw65 guid: (GUID fromString: '{4bfe3a86-e099-4d8e-9fd8-cf0fd761d8ad}')!
Gcilw65 comment: ''!
!Gcilw65 categoriesForClass!Unclassified! !
!Gcilw65 class methodsFor!

displayName

	^'32-bit 6.5.x'.
! !
!Gcilw65 class categoriesFor: #displayName!public! !

