"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw61
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw61 guid: (GUID fromString: '{496FFCA3-1D56-463F-8FDE-4838ABC55E9D}')!
Gcilw61 comment: ''!
!Gcilw61 categoriesForClass!Unclassified! !
!Gcilw61 class methodsFor!

displayName

	^'32-bit 6.1.x'.
! !
!Gcilw61 class categoriesFor: #displayName!public! !

