"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw67
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw67 guid: (GUID fromString: '{a9b59a34-89ae-41e6-90c8-67cc5e4407b3}')!
Gcilw67 comment: ''!
!Gcilw67 categoriesForClass!Unclassified! !
!Gcilw67 class methodsFor!

displayName

	^'32-bit 6.7.x'.
! !
!Gcilw67 class categoriesFor: #displayName!public! !

