"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw65
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw65 guid: (GUID fromString: '{4BFE3A86-E099-4D8E-9FD8-CF0FD761D8AD}')!
Gcilw65 comment: ''!
!Gcilw65 categoriesForClass!Unclassified! !
!Gcilw65 class methodsFor!

displayName

	^'32-bit 6.5.x'.
! !
!Gcilw65 class categoriesFor: #displayName!public! !

