"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw63
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw63 guid: (GUID fromString: '{0B266543-A4AF-485C-8572-C3ADD8C9DA70}')!
Gcilw63 comment: ''!
!Gcilw63 categoriesForClass!Unclassified! !
!Gcilw63 class methodsFor!

displayName

	^'32-bit 6.3.x'.
! !
!Gcilw63 class categoriesFor: #displayName!public! !

