"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw63
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw63 guid: (GUID fromString: '{0b266543-a4af-485c-8572-c3add8c9da70}')!
Gcilw63 comment: ''!
!Gcilw63 categoriesForClass!Unclassified! !
!Gcilw63 class methodsFor!

displayName

	^'32-bit 6.3.x'.
! !
!Gcilw63 class categoriesFor: #displayName!public! !

