"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcilw66
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcilw66 guid: (GUID fromString: '{f878e629-feaf-4205-a72a-c5140524da62}')!
Gcilw66 comment: ''!
!Gcilw66 categoriesForClass!Unclassified! !
!Gcilw66 class methodsFor!

displayName

	^'32-bit 6.6.x'.
! !
!Gcilw66 class categoriesFor: #displayName!public! !

