"Filed out from Dolphin Smalltalk 7"!

GciLibraryTestResource subclass: #GciMtLibraryTestResource
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GciMtLibraryTestResource guid: (GUID fromString: '{1BD46930-1AA5-41E9-8266-39D552586066}')!
GciMtLibraryTestResource comment: ''!
!GciMtLibraryTestResource categoriesForClass!Unclassified! !
!GciMtLibraryTestResource methodsFor!

libraryClass

	^LibGciMt_3_3! !
!GciMtLibraryTestResource categoriesFor: #libraryClass!private! !

