"Filed out from Dolphin Smalltalk 7"!

GciLibraryTestResource subclass: #GciMtLibraryTestResource
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GciMtLibraryTestResource guid: (GUID fromString: '{1bd46930-1aa5-41e9-8266-39d552586066}')!
GciMtLibraryTestResource comment: ''!
!GciMtLibraryTestResource categoriesForClass!Unclassified! !
!GciMtLibraryTestResource methodsFor!

libraryClass

	^LibGciMt_3_3! !
!GciMtLibraryTestResource categoriesFor: #libraryClass!private! !

