"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcirw62
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcirw62 guid: (GUID fromString: '{C2E42069-D534-4F0C-ACB8-1C11EC0EB3F7}')!
Gcirw62 comment: ''!
!Gcirw62 categoriesForClass!Unclassified! !
!Gcirw62 class methodsFor!

displayName

	^'32-bit 6.2.x'.
! !
!Gcirw62 class categoriesFor: #displayName!public! !

