"Filed out from Dolphin Smalltalk 7"!

Gcilw6x subclass: #Gcirw62
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Gcirw62 guid: (GUID fromString: '{c2e42069-d534-4f0c-acb8-1c11ec0eb3f7}')!
Gcirw62 comment: ''!
!Gcirw62 categoriesForClass!Unclassified! !
!Gcirw62 class methodsFor!

displayName

	^'32-bit 6.2.x'.
! !
!Gcirw62 class categoriesFor: #displayName!public! !

