"Filed out from Dolphin Smalltalk 7"!

GciSession24 subclass: #GciSession30
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GciSession30 guid: (GUID fromString: '{14522347-a353-4739-8139-f16c9c225058}')!
GciSession30 comment: ''!
!GciSession30 categoriesForClass!Unclassified! !
!GciSession30 methodsFor!

addRangeStopTo: stepPoints withSource: source

	GsMethod addRangeStopTo: stepPoints withSource: source.! !
!GciSession30 categoriesFor: #addRangeStopTo:withSource:!accessing!public! !

