"Filed out from Dolphin Smalltalk 7"!

DWORD subclass: #GciSessionId
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GciSessionId guid: (GUID fromString: '{63b7b17d-ee05-4344-8a1f-e3ec5abc32e8}')!
GciSessionId comment: ''!
!GciSessionId categoriesForClass!Unclassified! !
!GciSessionId methodsFor!

printOn: aStream

	self value printOn: aStream.
! !
!GciSessionId categoriesFor: #printOn:!public! !

