"Filed out from Dolphin Smalltalk 7"!

GciLibraryTestResource subclass: #GciTsLibraryTestResource
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GciTsLibraryTestResource guid: (GUID fromString: '{C367F335-6878-4D8F-9479-4181066A8922}')!
GciTsLibraryTestResource comment: ''!
!GciTsLibraryTestResource categoriesForClass!Unclassified! !
!GciTsLibraryTestResource methodsFor!

libraryClass

	^LibGciTs_3_3
! !
!GciTsLibraryTestResource categoriesFor: #libraryClass!private! !

