"Filed out from Dolphin Smalltalk 7"!

GciLibraryTestResource subclass: #GciTsLibraryTestResource
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GciTsLibraryTestResource guid: (GUID fromString: '{c367f335-6878-4d8f-9479-4181066a8922}')!
GciTsLibraryTestResource comment: ''!
!GciTsLibraryTestResource categoriesForClass!Unclassified! !
!GciTsLibraryTestResource methodsFor!

libraryClass

	^LibGciTs_3_3
! !
!GciTsLibraryTestResource categoriesFor: #libraryClass!private! !

