"Filed out from Dolphin Smalltalk 7"!

GsError subclass: #GsAnsiError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GsAnsiError guid: (GUID fromString: '{F7430395-3A25-4EEB-BC48-8AAE8EB0A73B}')!
GsAnsiError comment: ''!
!GsAnsiError categoriesForClass!Unclassified! !
!GsAnsiError class methodsFor!

wantsToHandle: aGciErrorSType session: aGciSession

	^false.
! !
!GsAnsiError class categoriesFor: #wantsToHandle:session:!public! !

