"Filed out from Dolphin Smalltalk 7"!

JadePresenterA subclass: #JadeUserPreferencesPresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeUserPreferencesPresenter guid: (GUID fromString: '{86fba099-1250-466b-9269-383895be897c}')!
JadeUserPreferencesPresenter comment: ''!
!JadeUserPreferencesPresenter categoriesForClass!Unclassified! !
