"Filed out from Dolphin Smalltalk 7"!

JadePresenter subclass: #JadeBrowserPresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeBrowserPresenter guid: (GUID fromString: '{D80D9891-A83E-456B-8849-D67E57E2A490}')!
JadeBrowserPresenter comment: ''!
!JadeBrowserPresenter categoriesForClass!Unclassified! !
!JadeBrowserPresenter methodsFor!

updateMenuBar: aMenuBar

! !
!JadeBrowserPresenter categoriesFor: #updateMenuBar:!public! !

