"Filed out from Dolphin Smalltalk 7"!

ValueDialog subclass: #JadeValueDialog
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
JadeValueDialog guid: (GUID fromString: '{C0B22B98-D493-48B6-A13A-1DE92E902CC5}')!
JadeValueDialog comment: ''!
!JadeValueDialog categoriesForClass!Unclassified! !
!JadeValueDialog class methodsFor!

icon

	^Icon fromFile: 'Jade\icons\GS32x32.ico'.
! !
!JadeValueDialog class categoriesFor: #icon!public! !

