"Filed out from Dolphin Smalltalk 7"!

DialogView subclass: #LayeredDialogView
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LayeredDialogView guid: (GUID fromString: '{5a9072ed-06cc-4da5-8c06-66054abb7d70}')!
LayeredDialogView comment: ''!
!LayeredDialogView categoriesForClass!Unclassified! !
!LayeredDialogView methodsFor!

extendedStyle

	^super extendedStyle bitOr: WS_EX_LAYERED.
! !
!LayeredDialogView categoriesFor: #extendedStyle!public! !

