"Filed out from Dolphin Smalltalk X6.1"!

DialogView subclass: #LayeredDialogView
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LayeredDialogView guid: (GUID fromString: '{5A9072ED-06CC-4DA5-8C06-66054ABB7D70}')!
LayeredDialogView comment: ''!
!LayeredDialogView categoriesForClass!Unclassified! !
!LayeredDialogView methodsFor!

extendedStyle

	^super extendedStyle bitOr: WS_EX_LAYERED.
! !
!LayeredDialogView categoriesFor: #extendedStyle!public! !

