"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_13
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_13 guid: (GUID fromString: '{ab8a5f68-b8a6-4fd7-9b22-a4977077f85b}')!
LibGciRpc64_3_2_13 comment: ''!
!LibGciRpc64_3_2_13 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_13 class methodsFor!

displayName

	^'64-bit 3.2.13'.
!

fileNameSearch

	^'libgcirpc-3.2.13-32.dll'.
! !
!LibGciRpc64_3_2_13 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_13 class categoriesFor: #fileNameSearch!public! !

