"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_3_06
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3_06 guid: (GUID fromString: '{174c6309-912a-4129-afca-8c0e28a135de}')!
LibGciRpc64_3_3_06 comment: ''!
!LibGciRpc64_3_3_06 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3_06 class methodsFor!

fileNameSearch

	^'libgcirpc-3.3.6-32.dll'.
! !
!LibGciRpc64_3_3_06 class categoriesFor: #fileNameSearch!public! !

