"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_17
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_17 guid: (GUID fromString: '{a16207a6-2139-4e73-8344-5bbd91b1600a}')!
LibGciRpc64_3_2_17 comment: ''!
!LibGciRpc64_3_2_17 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_17 class methodsFor!

displayName

	^'64-bit 3.2.17'.
!

fileNameSearch

	^'libgcirpc-3.2.17-32.dll'.
!

isRowanReady

	^true! !
!LibGciRpc64_3_2_17 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_17 class categoriesFor: #fileNameSearch!public! !
!LibGciRpc64_3_2_17 class categoriesFor: #isRowanReady!public!testing! !

