"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_20
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_20 guid: (GUID fromString: '{092F7B3C-B2E2-4238-8ACC-F7A381FE596D}')!
LibGciRpc64_20 comment: ''!
!LibGciRpc64_20 categoriesForClass!Unclassified! !
!LibGciRpc64_20 class methodsFor!

displayName

	^'64-bit 2.0.x'.
!

fileNameSearch

	^'libgcirpc64-205.dll'
! !
!LibGciRpc64_20 class categoriesFor: #displayName!public! !
!LibGciRpc64_20 class categoriesFor: #fileNameSearch!public! !

