"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_06
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_06 guid: (GUID fromString: '{81EB5050-FDDC-4907-9B98-69F01284C900}')!
LibGciRpc64_3_2_06 comment: ''!
!LibGciRpc64_3_2_06 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_06 class methodsFor!

displayName

	^'64-bit 3.2.6'.
!

fileNameSearch

	^'libgcirpc-3.2.6-32.dll'.
! !
!LibGciRpc64_3_2_06 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_06 class categoriesFor: #fileNameSearch!public! !

