"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_1 subclass: #LibGciRpc64_310x
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_310x guid: (GUID fromString: '{1a433237-482b-47c8-89db-541890bb91b8}')!
LibGciRpc64_310x comment: ''!
!LibGciRpc64_310x categoriesForClass!Unclassified! !
!LibGciRpc64_310x class methodsFor!

displayName

	^'64-bit 3.1.0.x'.
!

fileNameSearch

	^'libgcirpc-3.1.0.*-32.dll'.
! !
!LibGciRpc64_310x class categoriesFor: #displayName!public! !
!LibGciRpc64_310x class categoriesFor: #fileNameSearch!public! !

