"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_3_01
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3_01 guid: (GUID fromString: '{78687951-3f67-49a1-81b7-479121e13d23}')!
LibGciRpc64_3_3_01 comment: ''!
!LibGciRpc64_3_3_01 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3_01 class methodsFor!

displayName

	^'64-bit 3.3.1'.
!

fileNameSearch

	^'libgcirpc-3.3.1-32.dll'.
! !
!LibGciRpc64_3_3_01 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_3_01 class categoriesFor: #fileNameSearch!public! !

