"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_24
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_24 guid: (GUID fromString: '{4df6b51f-e61c-4046-9413-2db70136a4c1}')!
LibGciRpc64_24 comment: ''!
!LibGciRpc64_24 categoriesForClass!Unclassified! !
!LibGciRpc64_24 class methodsFor!

displayName

	^'64-bit 2.4.x'.
!

fileNameSearch

	^'libgcirpc64-244.dll'
! !
!LibGciRpc64_24 class categoriesFor: #displayName!public! !
!LibGciRpc64_24 class categoriesFor: #fileNameSearch!public! !

