"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_12
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_12 guid: (GUID fromString: '{90c77bc2-a48b-488e-bdf5-25d8ac8a0376}')!
LibGciRpc64_3_2_12 comment: ''!
!LibGciRpc64_3_2_12 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_12 class methodsFor!

displayName

	^'64-bit 3.2.12'.
!

fileNameSearch

	^'libgcirpc-3.2.12-32.dll'.
! !
!LibGciRpc64_3_2_12 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_12 class categoriesFor: #fileNameSearch!public! !

