"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_14
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_14 guid: (GUID fromString: '{df2548a9-7827-428a-aa8d-895e984868c1}')!
LibGciRpc64_3_2_14 comment: ''!
!LibGciRpc64_3_2_14 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_14 class methodsFor!

displayName

	^'64-bit 3.2.14'.
!

fileNameSearch

	^'libgcirpc-3.2.14-32.dll'.
! !
!LibGciRpc64_3_2_14 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_14 class categoriesFor: #fileNameSearch!public! !

