"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_3_03
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3_03 guid: (GUID fromString: '{1107452A-4FBB-4F98-8512-78CE69135D54}')!
LibGciRpc64_3_3_03 comment: ''!
!LibGciRpc64_3_3_03 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3_03 class methodsFor!

displayName

	^'64-bit 3.3.3'.
!

fileNameSearch

	^'libgcirpc-3.3.3-32.dll'.
! !
!LibGciRpc64_3_3_03 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_3_03 class categoriesFor: #fileNameSearch!public! !

