"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_4 subclass: #LibGciRpc64_3_5
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_5 guid: (GUID fromString: '{50640f87-32a5-4a8e-bd7c-6d4c072b87b7}')!
LibGciRpc64_3_5 comment: ''!
!LibGciRpc64_3_5 categoriesForClass!Unclassified! !
!LibGciRpc64_3_5 class methodsFor!

displayName

	^'64-bit 3.5.0'.
!

fileNameSearch

	^'libgcirpc-3.5.0-32.dll'.
! !
!LibGciRpc64_3_5 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_5 class categoriesFor: #fileNameSearch!public! !

