"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_01
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_01 guid: (GUID fromString: '{9b3a8d44-3e44-49ac-90c5-afda22e1cd1b}')!
LibGciRpc64_3_2_01 comment: ''!
!LibGciRpc64_3_2_01 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_01 class methodsFor!

displayName

	^'64-bit 3.2.1'.
!

fileNameSearch

	^'libgcirpc-3.2.1-32.dll'.
! !
!LibGciRpc64_3_2_01 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_01 class categoriesFor: #fileNameSearch!public! !

