"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_10
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_10 guid: (GUID fromString: '{4ef14b8f-3bf8-4484-9a0c-4b2468f46491}')!
LibGciRpc64_3_2_10 comment: ''!
!LibGciRpc64_3_2_10 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_10 class methodsFor!

displayName

	^'64-bit 3.2.10'.
!

fileNameSearch

	^'libgcirpc-3.2.10-32.dll'.
! !
!LibGciRpc64_3_2_10 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_10 class categoriesFor: #fileNameSearch!public! !

