"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_07
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_07 guid: (GUID fromString: '{ed635505-59e8-42e5-87a5-47c0e655e5fc}')!
LibGciRpc64_3_2_07 comment: ''!
!LibGciRpc64_3_2_07 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_07 class methodsFor!

displayName

	^'64-bit 3.2.7'.
!

fileNameSearch

	^'libgcirpc-3.2.7-32.dll'.
! !
!LibGciRpc64_3_2_07 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_07 class categoriesFor: #fileNameSearch!public! !

