"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_02
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_02 guid: (GUID fromString: '{BD5DC8E2-7DCC-48E3-B0B8-9F73D810E6E6}')!
LibGciRpc64_3_2_02 comment: ''!
!LibGciRpc64_3_2_02 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_02 class methodsFor!

displayName

	^'64-bit 3.2.2'.
!

fileNameSearch

	^'libgcirpc-3.2.2-32.dll'.
! !
!LibGciRpc64_3_2_02 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_02 class categoriesFor: #fileNameSearch!public! !

