"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_23
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_23 guid: (GUID fromString: '{D51C9D71-CC8F-4BC9-B4B5-946F772BFC1B}')!
LibGciRpc64_23 comment: ''!
!LibGciRpc64_23 categoriesForClass!Unclassified! !
!LibGciRpc64_23 class methodsFor!

displayName

	^'64-bit 2.3.x'.
! !
!LibGciRpc64_23 class categoriesFor: #displayName!public! !

