"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_3_04
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3_04 guid: (GUID fromString: '{66d07089-a5aa-4c28-89d6-ca41ff47fa26}')!
LibGciRpc64_3_3_04 comment: ''!
!LibGciRpc64_3_3_04 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3_04 class methodsFor!

displayName

	^'64-bit 3.3.4'.
!

fileNameSearch

	^'libgcirpc-3.3.4-32.dll'.
! !
!LibGciRpc64_3_3_04 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_3_04 class categoriesFor: #fileNameSearch!public! !

