"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_4 subclass: #LibGciRpc64_3_4_1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_4_1 guid: (GUID fromString: '{8d392c04-9bff-4011-85db-96db6c0ed0f4}')!
LibGciRpc64_3_4_1 comment: ''!
!LibGciRpc64_3_4_1 categoriesForClass!Unclassified! !
!LibGciRpc64_3_4_1 class methodsFor!

displayName

	^'64-bit 3.4.1'.
!

fileNameSearch

	^'libgcirpc-3.4.1-32.dll'.
! !
!LibGciRpc64_3_4_1 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_4_1 class categoriesFor: #fileNameSearch!public! !

