"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_10
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_10 guid: (GUID fromString: '{4EF14B8F-3BF8-4484-9A0C-4B2468F46491}')!
LibGciRpc64_3_2_10 comment: ''!
!LibGciRpc64_3_2_10 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_10 class methodsFor!

displayName

	^'64-bit 3.2.10'.
!

fileNameSearch

	^'libgcirpc-3.2.10-32.dll'.
! !
!LibGciRpc64_3_2_10 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_10 class categoriesFor: #fileNameSearch!public! !

