"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_08
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_08 guid: (GUID fromString: '{e31f62fc-c1ee-40c6-90d4-a59dda3c831b}')!
LibGciRpc64_3_2_08 comment: ''!
!LibGciRpc64_3_2_08 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_08 class methodsFor!

displayName

	^'64-bit 3.2.8'.
!

fileNameSearch

	^'libgcirpc-3.2.8-32.dll'.
! !
!LibGciRpc64_3_2_08 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_08 class categoriesFor: #fileNameSearch!public! !

