"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_21
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_21 guid: (GUID fromString: '{95100075-9a56-4116-ad62-415290b2ba64}')!
LibGciRpc64_21 comment: ''!
!LibGciRpc64_21 categoriesForClass!Unclassified! !
!LibGciRpc64_21 class methodsFor!

displayName

	^'64-bit 2.1.x'.
!

fileNameSearch

	^'libgcirpc64-214.dll'
! !
!LibGciRpc64_21 class categoriesFor: #displayName!public! !
!LibGciRpc64_21 class categoriesFor: #fileNameSearch!public! !

