"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_16
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_16 guid: (GUID fromString: '{6151f972-2ce3-4f2a-8716-f09f0630bdb2}')!
LibGciRpc64_3_2_16 comment: ''!
!LibGciRpc64_3_2_16 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_16 class methodsFor!

displayName

	^'64-bit 3.2.16'.
!

fileNameSearch

	^'libgcirpc-3.2.16-32.dll'.
! !
!LibGciRpc64_3_2_16 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_16 class categoriesFor: #fileNameSearch!public! !

