"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_4
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_4 guid: (GUID fromString: '{96c1e982-82a2-431a-9cc0-abfb2fc4e7e1}')!
LibGciRpc64_3_4 comment: ''!
!LibGciRpc64_3_4 categoriesForClass!Unclassified! !
!LibGciRpc64_3_4 class methodsFor!

fileNameSearch

	^'libgcirpc-3.4.0-32.dll'.
! !
!LibGciRpc64_3_4 class categoriesFor: #fileNameSearch!public! !

