"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_13
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_13 guid: (GUID fromString: '{AB8A5F68-B8A6-4FD7-9B22-A4977077F85B}')!
LibGciRpc64_3_2_13 comment: ''!
!LibGciRpc64_3_2_13 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_13 class methodsFor!

displayName

	^'64-bit 3.2.13'.
!

fileNameSearch

	^'libgcirpc-3.2.13-32.dll'.
! !
!LibGciRpc64_3_2_13 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_13 class categoriesFor: #fileNameSearch!public! !

