"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_3_05
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3_05 guid: (GUID fromString: '{441ababf-871b-4370-940c-91c646dc1187}')!
LibGciRpc64_3_3_05 comment: ''!
!LibGciRpc64_3_3_05 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3_05 class methodsFor!

displayName

	^'64-bit 3.3.5'.
!

fileNameSearch

	^'libgcirpc-3.3.5-32.dll'.
! !
!LibGciRpc64_3_3_05 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_3_05 class categoriesFor: #fileNameSearch!public! !

