"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_20
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_20 guid: (GUID fromString: '{092f7b3c-b2e2-4238-8acc-f7a381fe596d}')!
LibGciRpc64_20 comment: ''!
!LibGciRpc64_20 categoriesForClass!Unclassified! !
!LibGciRpc64_20 class methodsFor!

displayName

	^'64-bit 2.0.x'.
!

fileNameSearch

	^'libgcirpc64-205.dll'
! !
!LibGciRpc64_20 class categoriesFor: #displayName!public! !
!LibGciRpc64_20 class categoriesFor: #fileNameSearch!public! !

