"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3_0 subclass: #LibGciRpc64_3_4_0
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_4_0 guid: (GUID fromString: '{96c1e982-82a2-431a-9cc0-abfb2fc4e7e1}')!
LibGciRpc64_3_4_0 comment: ''!
!LibGciRpc64_3_4_0 categoriesForClass!Unclassified! !
!LibGciRpc64_3_4_0 methodsFor!

verifyEnvironment: anInteger
	"Other environments supported"! !
!LibGciRpc64_3_4_0 categoriesFor: #verifyEnvironment:!public! !

