"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_24
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_24 guid: (GUID fromString: '{4DF6B51F-E61C-4046-9413-2DB70136A4C1}')!
LibGciRpc64_24 comment: ''!
!LibGciRpc64_24 categoriesForClass!Unclassified! !
!LibGciRpc64_24 class methodsFor!

displayName

	^'64-bit 2.4.x'.
! !
!LibGciRpc64_24 class categoriesFor: #displayName!public! !

