"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_22
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_22 guid: (GUID fromString: '{5D1A9DC4-2B15-4DA9-93B0-851D62109E88}')!
LibGciRpc64_22 comment: ''!
!LibGciRpc64_22 categoriesForClass!Unclassified! !
!LibGciRpc64_22 class methodsFor!

displayName

	^'64-bit 2.2.x'.
! !
!LibGciRpc64_22 class categoriesFor: #displayName!public! !

