"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_04
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_04 guid: (GUID fromString: '{AE6862DF-767F-45A7-8CF0-2520FDD79C28}')!
LibGciRpc64_3_2_04 comment: ''!
!LibGciRpc64_3_2_04 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_04 class methodsFor!

displayName

	^'64-bit 3.2.4'.
!

fileNameSearch

	^'libgcirpc-3.2.4-32.dll'.
! !
!LibGciRpc64_3_2_04 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_04 class categoriesFor: #fileNameSearch!public! !

