"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_03
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_03 guid: (GUID fromString: '{7cd3d48a-c954-4465-8dbc-90511a44e6e3}')!
LibGciRpc64_3_2_03 comment: ''!
!LibGciRpc64_3_2_03 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_03 class methodsFor!

displayName

	^'64-bit 3.2.3'.
!

fileNameSearch

	^'libgcirpc-3.2.3-32.dll'.
! !
!LibGciRpc64_3_2_03 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_03 class categoriesFor: #fileNameSearch!public! !

