"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_15
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_15 guid: (GUID fromString: '{b6a4bc2b-3620-4342-99fc-8173f510f7fb}')!
LibGciRpc64_3_2_15 comment: ''!
!LibGciRpc64_3_2_15 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_15 class methodsFor!

fileNameSearch

	^'libgcirpc-3.2.15-32.dll'.
! !
!LibGciRpc64_3_2_15 class categoriesFor: #fileNameSearch!public! !

