"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_2 subclass: #LibGciRpc64_3_2_09
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_2_09 guid: (GUID fromString: '{12081231-C77F-4BC8-8F36-DD11BDBB44CD}')!
LibGciRpc64_3_2_09 comment: ''!
!LibGciRpc64_3_2_09 categoriesForClass!Unclassified! !
!LibGciRpc64_3_2_09 class methodsFor!

displayName

	^'64-bit 3.2.9'.
!

fileNameSearch

	^'libgcirpc-3.2.9-32.dll'.
! !
!LibGciRpc64_3_2_09 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_2_09 class categoriesFor: #fileNameSearch!public! !

