"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_22
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_22 guid: (GUID fromString: '{5d1a9dc4-2b15-4da9-93b0-851d62109e88}')!
LibGciRpc64_22 comment: ''!
!LibGciRpc64_22 categoriesForClass!Unclassified! !
!LibGciRpc64_22 class methodsFor!

displayName

	^'64-bit 2.2.x'.
!

fileNameSearch

	^'libgcirpc64-225.dll'
! !
!LibGciRpc64_22 class categoriesFor: #displayName!public! !
!LibGciRpc64_22 class categoriesFor: #fileNameSearch!public! !

