"Filed out from Dolphin Smalltalk 7"!

GciMultiThreadedLibrary subclass: #LibGciRpc64_3_3
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3 guid: (GUID fromString: '{68DB187D-A739-41BE-AD58-A476218B1B04}')!
LibGciRpc64_3_3 comment: ''!
!LibGciRpc64_3_3 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3 methodsFor!

errorStructureClass

	^GciErrSType64_31.
!

threadSafeLibraryName

	^'libgcits-3.3.0-32.dll'
! !
!LibGciRpc64_3_3 categoriesFor: #errorStructureClass!private! !
!LibGciRpc64_3_3 categoriesFor: #threadSafeLibraryName!private! !

!LibGciRpc64_3_3 class methodsFor!

displayName

	^'64-bit 3.3.0 (MT)'.
!

fileNameSearch

	^'libgcimt-3.3.0-32.dll'.
! !
!LibGciRpc64_3_3 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_3 class categoriesFor: #fileNameSearch!public! !

