"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64_3_3 subclass: #LibGciRpc64_3_3_01
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_3_3_01 guid: (GUID fromString: '{78687951-3F67-49A1-81B7-479121E13D23}')!
LibGciRpc64_3_3_01 comment: ''!
!LibGciRpc64_3_3_01 categoriesForClass!Unclassified! !
!LibGciRpc64_3_3_01 class methodsFor!

displayName

	^'64-bit 3.3.1'.
!

fileNameSearch

	^'libgcirpc-3.3.1-32.dll'.
! !
!LibGciRpc64_3_3_01 class categoriesFor: #displayName!public! !
!LibGciRpc64_3_3_01 class categoriesFor: #fileNameSearch!public! !

