"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_23
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_23 guid: (GUID fromString: '{d51c9d71-cc8f-4bc9-b4b5-946f772bfc1b}')!
LibGciRpc64_23 comment: ''!
!LibGciRpc64_23 categoriesForClass!Unclassified! !
!LibGciRpc64_23 class methodsFor!

displayName

	^'64-bit 2.3.x'.
!

fileNameSearch

	^'libgcirpc64-230.dll'
! !
!LibGciRpc64_23 class categoriesFor: #displayName!public! !
!LibGciRpc64_23 class categoriesFor: #fileNameSearch!public! !

