"Filed out from Dolphin Smalltalk 7"!

LibGciRpc64 subclass: #LibGciRpc64_21
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LibGciRpc64_21 guid: (GUID fromString: '{95100075-9A56-4116-AD62-415290B2BA64}')!
LibGciRpc64_21 comment: ''!
!LibGciRpc64_21 categoriesForClass!Unclassified! !
!LibGciRpc64_21 class methodsFor!

displayName

	^'64-bit 2.1.x'.
! !
!LibGciRpc64_21 class categoriesFor: #displayName!public! !

