"Filed out from Dolphin Smalltalk 7"!

MCPatchOperation subclass: #MCAddition
	instanceVariableNames: 'definition'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MCAddition guid: (GUID fromString: '{b78cb54f-d86c-4398-a734-2c5cfa934104}')!
MCAddition comment: ''!
!MCAddition categoriesForClass!Unclassified! !
!MCAddition methodsFor!

className

	^definition className.
!

detailsString

	^definition detailsString.
!

modificationMemo

	^definition displayMemo.
!

modificationText

	^definition displayText.
!

selector

	^definition selector.
! !
!MCAddition categoriesFor: #className!public! !
!MCAddition categoriesFor: #detailsString!public! !
!MCAddition categoriesFor: #modificationMemo!public! !
!MCAddition categoriesFor: #modificationText!public! !
!MCAddition categoriesFor: #selector!public! !

