"Filed out from Dolphin Smalltalk 7"!

MCDefinition subclass: #MCClassDefinition
	instanceVariableNames: 'className definition'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MCClassDefinition guid: (GUID fromString: '{4d46b46e-f290-4992-93c5-79caee623c11}')!
MCClassDefinition comment: ''!
!MCClassDefinition categoriesForClass!Unclassified! !
!MCClassDefinition methodsFor!

className

	^className.
!

detailsString

	^'Class Definition'.
!

displayMemo

	^definition.
!

displayText

	^'displayText'.
! !
!MCClassDefinition categoriesFor: #className!public! !
!MCClassDefinition categoriesFor: #detailsString!public! !
!MCClassDefinition categoriesFor: #displayMemo!public! !
!MCClassDefinition categoriesFor: #displayText!public! !

