"Filed out from Dolphin Smalltalk 7"!

MCDirectoryRepository subclass: #MCServerDirectoryRepository
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MCServerDirectoryRepository guid: (GUID fromString: '{45fee87b-b286-47b5-852a-e006bfb4fc16}')!
MCServerDirectoryRepository comment: ''!
!MCServerDirectoryRepository categoriesForClass!Unclassified! !
