"Filed out from Dolphin Smalltalk 7"!

DWORDField subclass: #OopType32Field
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OopType32Field guid: (GUID fromString: '{1C990F84-794B-4897-9C03-F58DF5ACAE69}')!
OopType32Field comment: ''!
!OopType32Field categoriesForClass!Unclassified! !
!OopType32Field methodsFor!

fieldClass

	^OopType32.! !
!OopType32Field categoriesFor: #fieldClass!public! !

