"Filed out from Dolphin Smalltalk 7"!

QWORDField subclass: #OopType64Field
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
OopType64Field guid: (GUID fromString: '{7ed7d17b-7fc5-4857-89c3-5a27ac9de8ad}')!
OopType64Field comment: ''!
!OopType64Field categoriesForClass!Unclassified! !
!OopType64Field methodsFor!

fieldClass

	^OopType64.! !
!OopType64Field categoriesFor: #fieldClass!public! !

