"Filed out from Dolphin Smalltalk 7"!

RowanClassesUpdate subclass: #RowanMethodsUpdate
	instanceVariableNames: 'methods methodFilters selectors selectedClass selectedSelectors'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanMethodsUpdate guid: (GUID fromString: '{253447c0-f306-48b9-87c4-7bfa4516f3b3}')!
RowanMethodsUpdate comment: ''!
!RowanMethodsUpdate categoriesForClass!Unclassified! !
