"Filed out from Dolphin Smalltalk 7"!

RowanCommandResult subclass: #RowanClassCategoryUpdate
	instanceVariableNames: 'categories selection'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanClassCategoryUpdate guid: (GUID fromString: '{16db26a6-218c-475f-9cfb-039e5613152f}')!
RowanClassCategoryUpdate comment: ''!
!RowanClassCategoryUpdate categoriesForClass!Unclassified! !
