"Filed out from Dolphin Smalltalk 7"!

RowanCommandResult subclass: #RowanPackageUpdate
	instanceVariableNames: 'packages modifiedPackages selections'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPackageUpdate guid: (GUID fromString: '{4c15535a-fac8-439c-bf9d-abf04a2949f4}')!
RowanPackageUpdate comment: ''!
!RowanPackageUpdate categoriesForClass!Unclassified! !
