"Filed out from Dolphin Smalltalk 7"!

RowanCommandResult subclass: #RowanDictionaryUpdate
	instanceVariableNames: 'dictionaries selections'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanDictionaryUpdate guid: (GUID fromString: '{83fbbd49-2c42-4bef-8463-1e3264cbcc43}')!
RowanDictionaryUpdate comment: ''!
!RowanDictionaryUpdate categoriesForClass!Unclassified! !
