"Filed out from Dolphin Smalltalk 7"!

RowanCommandResult subclass: #RowanClassInfoUpdate
	instanceVariableNames: 'oop template category comment'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanClassInfoUpdate guid: (GUID fromString: '{e7acaa37-9865-4b18-a3d9-680bccb6db7c}')!
RowanClassInfoUpdate comment: ''!
!RowanClassInfoUpdate categoriesForClass!Unclassified! !
