"Filed out from Dolphin Smalltalk 7"!

RowanPackageService subclass: #RowanPackageDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanPackageDefinitionService guid: (GUID fromString: '{9c32ad01-abf2-4999-bba2-6675b6ad5fc6}')!
RowanPackageDefinitionService comment: 'Placeholder until the server service classes are renamed'!
!RowanPackageDefinitionService categoriesForClass!Kernel-Objects! !
