"Filed out from Dolphin Smalltalk 7"!

RowanService subclass: #RowanVariableService
	instanceVariableNames: 'oop key value'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanVariableService guid: (GUID fromString: '{7fef01ea-b803-4a8a-bb67-843c948bbc31}')!
RowanVariableService comment: ''!
!RowanVariableService categoriesForClass!Kernel-Objects! !
!RowanVariableService methodsFor!

key
	^oop printString -> key!

value

	^value! !
!RowanVariableService categoriesFor: #key!public! !
!RowanVariableService categoriesFor: #value!public! !

