"Filed out from Dolphin Smalltalk 7"!

RowanMethodService subclass: #RowanMethodDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanMethodDefinitionService guid: (GUID fromString: '{d07ef783-49bc-4926-8a75-5fef370a8ac5}')!
RowanMethodDefinitionService comment: 'Placeholder until the server service classes are renamed'!
!RowanMethodDefinitionService categoriesForClass!Kernel-Objects! !
