"Filed out from Dolphin Smalltalk 7"!

RowanProjectService subclass: #RowanProjectDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanProjectDefinitionService guid: (GUID fromString: '{1d414eef-8cc6-4e3a-b744-3a5faec85b93}')!
RowanProjectDefinitionService comment: 'Placeholder until the server service classes are renamed'!
!RowanProjectDefinitionService categoriesForClass!Unclassified! !
