"Filed out from Dolphin Smalltalk 7"!

Error subclass: #RowanDebuggerStepPointError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanDebuggerStepPointError guid: (GUID fromString: '{6f572ac8-2ed4-4f1a-aab6-47e28ac6fb01}')!
RowanDebuggerStepPointError comment: ''!
!RowanDebuggerStepPointError categoriesForClass!Kernel-Exception Handling! !
