"Filed out from Dolphin Smalltalk 7"!

RowanDefinitionService subclass: #RowanClassDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanClassDefinitionService guid: (GUID fromString: '{ab96bbd9-d725-4add-b635-94cec9f12a19}')!
RowanClassDefinitionService comment: ''!
!RowanClassDefinitionService categoriesForClass!Kernel-Objects! !
