"Filed out from Dolphin Smalltalk 7"!

MethodSourcePresenter subclass: #RowanMethodSourcePresenter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanMethodSourcePresenter guid: (GUID fromString: '{cfc0ca1c-9636-45a9-bc23-ceca124a04cd}')!
RowanMethodSourcePresenter comment: ''!
!RowanMethodSourcePresenter categoriesForClass!Unclassified! !
!RowanMethodSourcePresenter methodsFor!

updateMethodStepPoints

	self rowanFixMe.
	! !
!RowanMethodSourcePresenter categoriesFor: #updateMethodStepPoints!public! !

