"Filed out from Dolphin Smalltalk 7"!

JadeShell subclass: #RowanShell
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanShell guid: (GUID fromString: '{5f8c3e73-3052-4bc8-9dcf-db49fb1968ad}')!
RowanShell comment: ''!
!RowanShell categoriesForClass!Unclassified! !
!RowanShell methodsFor!

shellName

	^'Rowan Shell'.
! !
!RowanShell categoriesFor: #shellName!private! !

