"Filed out from Dolphin Smalltalk 7"!

RowanCommandResult subclass: #RowanMethodUpdate
	instanceVariableNames: 'classOop className methodOop selector category editable source firstSendOffsets stepPoints breakPoints originalMethodSource compilationWarnings'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanMethodUpdate guid: (GUID fromString: '{c77aaf73-dce8-4890-a7b9-dcbe34ac585c}')!
RowanMethodUpdate comment: ''!
!RowanMethodUpdate categoriesForClass!Unclassified! !
