"Filed out from Dolphin Smalltalk 7"!

RowanClassService subclass: #RowanClassDefinitionService
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RowanClassDefinitionService guid: (GUID fromString: '{df7fa357-59f4-4de7-a7e8-557636b229ce}')!
RowanClassDefinitionService comment: 'Placeholder until the server service classes are renamed'!
!RowanClassDefinitionService categoriesForClass!Kernel-Objects! !
