"Filed out from Dolphin Smalltalk 7"!

GsHostProcess subclass: #SharedPageCacheMonitor
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SharedPageCacheMonitor guid: (GUID fromString: '{81611ff5-3795-4f5a-83d0-98c55159048a}')!
SharedPageCacheMonitor comment: ''!
!SharedPageCacheMonitor categoriesForClass!Unclassified! !
!SharedPageCacheMonitor methodsFor!

processType

	^'Cache'.
! !
!SharedPageCacheMonitor categoriesFor: #processType!public! !

!SharedPageCacheMonitor class methodsFor!

type

	^'cache'.
! !
!SharedPageCacheMonitor class categoriesFor: #type!public! !

