"Filed out from Dolphin Smalltalk 7"!

Object subclass: #STON
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
STON guid: (GUID fromString: '{22c8c7aa-152f-45c6-b5f2-9843ed78d322}')!
STON comment: ''!
!STON categoriesForClass!Kernel-Objects! !
!STON class methodsFor!

reader
	^STONReader new allowComplexMapKeys: true! !
!STON class categoriesFor: #reader!public! !

